export DOT_FILES=$HOME/dot-files

# Load custom config files.
for file in $DOT_FILES/{colors,aliases,functions}; do
  [ -r "$file" ] && source "$file"
done
unset file

# Source dependencies.
if [ -f ~/.nvm/nvm.sh ]; then
  source ~/.nvm/nvm.sh
  nvm alias default iojs > /dev/null
  export NODE_PATH=$(npm root -g):$NODE_PATH
fi
if [ -d ~/.rbenv ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
  rbenv global 2.2.0
fi
if [ -f $DOT_FILES/vendor/z/z.sh ]; then
  source $DOT_FILES/vendor/z/z.sh
fi

# Load ENV variable definitions and overrides.
source $DOT_FILES/exports

# Load machine-specific config if it's there.
if [ -f $DOT_FILES/custom ]; then
  source $DOT_FILES/custom
fi

# Make certain keyboard shortcuts available.
stty -ixon

# Set up zsh.
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="whastings"
ZSH_CUSTOM=$DOT_FILES/zsh
plugins=(vi-mode bundler extract rails whastings)
source $ZSH/oh-my-zsh.sh

# Enter tmux if it's available.
if [ type -P tmux &>/dev/null ]; then
  $DOT_FILES/scripts/enter-default-tmux
fi
