#!/usr/bin/env bash

container_exists=$(docker inspect --format {{.Id}} pg 2> /dev/null)

if [[ -z "$container_exists" ]]; then
  docker run \
    --name=pg \
    --publish=5432:5432 \
    -e POSTGRES_USER=root \
    -e POSTGRES_PASSWORD=root \
    -d \
    postgres
else
  echo "Postgres docker container already exists"
fi
