#!/usr/bin/env bash
# Source: http://superuser.com/questions/611538/is-there-a-way-to-display-a-countdown-or-stopwatch-timer-in-a-terminal

date1=`date +%s`;
while true; do
  echo -ne "$(date -u --date @$((`date +%s` - $date1)) +%H:%M:%S)\r";
  sleep 0.1
done
